export const serviceSectorList = [
  "Mobile Phones Repair",
  "Car Repair & Maintenance",
  "Electrical Services",
  "Plumbing Services",
  "Home Cleaning",
  "Appliance Repair",
  "IT & Computer Support",
  "Painting Services",
  "HVAC (Heating, Ventilation, Air Conditioning) Services",
  "Carpentry Services",
  "Roofing Services",
  "Pest Control",
  "Landscaping & Gardening",
  "Locksmith Services",
  "General Handyman Services",
  "Laundry & Dry Cleaning",
  "Interior Design & Renovation",
  "Fitness & Personal Training",
  "Beauty & Salon Services",
  "Photography & Videography",
  "Tutoring & Educational Services",
  "Pet Care & Grooming",
  "Moving & Relocation Services",
  "Car Wash & Detailing",
  "Event Planning & Catering",
  "Massage Therapy",
  "Bicycle Repair",
  "Web Design & Development",
  "Graphic Design",
  "Makeup Artist Services",
  "Music Lessons",
  "Fitness Equipment Repair",
  "Waterproofing Services",
  "Automobile Detailing & Customization",
];
